name: Publish to Sonatype

on:
  release:
    types: [published]
  workflow_dispatch:  # Manually triggered workflow event

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Publish to Sonatype
      run: ./gradlew publishToSonatype
